"""Puerto de persistencia del registry. Una transacción es todo o nada (spec §5.4)."""

from collections.abc import Sequence
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Literal, Protocol

from agent_core.registry.blobs import BlobStore
from agent_core.registry.models import (
    AliasChange,
    Approval,
    DraftWrite,
    EntityDraft,
    EvalRun,
    PauseState,
    Proposal,
    RegistryEvent,
    StoredRelease,
    StoredVersion,
    VersionRef,
)

Status = Literal["active", "revoked"]


class RegistryTx(Protocol):
    blobs: BlobStore

    def get_proposal(self, proposal_id: str, *, for_update: bool = False) -> Proposal | None: ...
    def save_proposal(self, proposal: Proposal) -> None: ...
    def list_proposals(self) -> list[Proposal]:
        """Todas las propuestas; el filtro, el orden y la página los pone el servicio."""
        ...
    def get_changes(self, proposal_id: str) -> list[EntityDraft]: ...
    def replace_changes(self, proposal_id: str, drafts: Sequence[EntityDraft]) -> None: ...
    def get_version(self, ref: VersionRef) -> StoredVersion | None: ...
    def list_versions(self, kind: str, entity_id: str) -> list[StoredVersion]: ...
    def insert_version(self, version: StoredVersion) -> None: ...
    def get_release(self, release_id: str) -> StoredRelease | None: ...
    def release_refs(self, release_id: str) -> list[VersionRef]: ...
    def insert_release(self, stored: StoredRelease, refs: Sequence[VersionRef]) -> None: ...
    def release_status(self, release_id: str) -> Status | None: ...
    def set_release_status(self, release_id: str, status: Status) -> None: ...
    def latest_release_for_agent_version(self, agent_id: str, version: str) -> str | None: ...
    def lock_agent(self, agent_id: str) -> None:
        """Serializa las escrituras de releases de un agente hasta el fin de la transacción (spec §5.4.1).

        `FOR UPDATE` sobre un alias que aún no existe no bloquea a nadie; esto sí."""
        ...
    def get_alias(self, agent_id: str, alias: str, *, for_update: bool = False) -> str | None: ...
    def set_alias(self, change: AliasChange) -> None: ...
    def get_pause(self, agent_id: str, *, for_update: bool = False) -> PauseState | None: ...
    def set_pause(self, state: PauseState) -> None: ...
    def paused_agents(self) -> set[str]: ...
    def aliases_to(self, release_id: str) -> list[tuple[str, str]]: ...
    def aliases_named(self, alias: str) -> list[tuple[str, str]]:
        """`(agent_id, release_id)` of every agent holding this alias, sorted by agent id."""
        ...
    def insert_eval_run(self, run: EvalRun) -> None: ...
    def latest_eval_run(self, proposal_id: str, candidate_hash: str) -> EvalRun | None: ...
    def insert_approval(self, approval: Approval) -> None: ...
    def latest_approval(self, proposal_id: str, candidate_hash: str) -> Approval | None: ...
    def latest_decision(self, proposal_id: str) -> Approval | None: ...
    def append_event(self, event: RegistryEvent) -> None: ...
    def events(self) -> list[RegistryEvent]: ...
    def get_publish_key(self, key: str) -> tuple[str, str] | None: ...
    def put_publish_key(self, key: str, proposal_id: str, release_id: str) -> None: ...
    def get_draft_write(self, key: str) -> DraftWrite | None: ...
    def put_draft_write(self, write: DraftWrite) -> None: ...
    def get_eval_run(self, eval_run_id: str) -> EvalRun | None: ...
    def count_created_after(self, origin: str, after: datetime) -> int:
        """Propuestas creadas con ese origen en `at > after` (ventana móvil de los topes)."""
        ...
    def count_eval_runs(self, proposal_id: str) -> int: ...


class RegistryStore(Protocol):
    def transaction(self) -> AbstractContextManager[RegistryTx]: ...
