"""M0 — dominio: tipos, esquemas de nodos, eventos, errores y serialización canónica."""

from agent_core.domain.base import (
    EntityId,
    ExactVersion,
    Locale,
    Model,
    MutableModel,
    NodeId,
    Probability,
    UtcDatetime,
)
from agent_core.domain.entities import (
    ENTITY_KIND,
    Agent,
    Budgets,
    CalibrationRef,
    DecisionModelDef,
    EngineTemplates,
    EscalateAction,
    Flow,
    InjectionRule,
    InjectionRuleset,
    Interrupt,
    KnowledgePage,
    KnowledgeSnapshot,
    LanguageDetection,
    ModelPrice,
    ModelProfile,
    Policy,
    Prompt,
    ProviderSpec,
    RegistryEntity,
    Release,
    RiskClass,
    StartFlowAction,
    StructuredMode,
    Template,
    ToolDef,
)
from agent_core.domain.errors import (
    PROBLEM_STATUS,
    CredentialsInvalid,
    DomainError,
    EngineError,
    GatewayError,
    GatewayErrorKind,
    IllegalTransition,
    InvalidRuntimeRef,
    ProblemCode,
    SchemaError,
    TurnInProgress,
    VersionConflict,
)
from agent_core.domain.events import (
    EVENT_EMITTERS,
    EVENT_TYPES,
    MEASURED_FIELDS,
    AccessDenied,
    AccessDeniedPayload,
    AccessDeniedReason,
    ActionCancelled,
    ActionCancelledPayload,
    ActionConfirmed,
    ActionConfirmedPayload,
    ActionDispatched,
    ActionDispatchedPayload,
    ActionVerified,
    ActionVerifiedPayload,
    AgentStep,
    AgentStepPayload,
    AnyEvent,
    CommandEmitted,
    CommandEmittedPayload,
    DecisionMade,
    DecisionMadePayload,
    EngineEvent,
    Escalated,
    EscalatedPayload,
    ExpiryEvaluated,
    ExpiryEvaluatedPayload,
    GuardsOutput,
    HandoffCreatedPayload,
    HandoffResolved,
    HandoffResolvedPayload,
    InjectionFlagged,
    InjectionFlaggedPayload,
    InjectionGuard,
    LabelScore,
    LangGuard,
    LangScore,
    LlmUsage,
    NodeEntered,
    NodeEnteredPayload,
    ResponseEmitted,
    ResponseEmittedPayload,
    ResponseFailed,
    ResponseFailedPayload,
    RuleEvaluated,
    RuleEvaluatedPayload,
    RunClosed,
    RunClosedPayload,
    RunStarted,
    RunStartedPayload,
    StepUpRequested,
    StepUpRequestedPayload,
    ToolCalled,
    ToolCalledPayload,
    TurnCompleted,
    TurnCompletedPayload,
    TurnStages,
    TurnStarted,
    TurnStartedPayload,
    ValidatorOutcome,
)
from agent_core.domain.identity import (
    AuthInfo,
    AuthLevel,
    OnBehalfOf,
    Principal,
    PrincipalKey,
    PrincipalType,
    SubjectRef,
)
from agent_core.domain.json import (
    JsonValue,
    canonical_bytes,
    dumps,
    loads,
    sha256_hex,
    to_jsonable,
)
from agent_core.domain.nodes import (
    MVP_NODE_KINDS,
    PRODUCTION_NODE_KINDS,
    RESULTS,
    TERMINAL,
    WAITING,
    ActionSpec,
    AgentNode,
    AgentNodeConfig,
    Approver,
    AwaitApprovalConfig,
    AwaitApprovalNode,
    CollectConfig,
    CollectNode,
    ConfirmConfig,
    ConfirmNode,
    DecideConfig,
    DecideNode,
    EndConfig,
    EndNode,
    EscalateConfig,
    EscalateNode,
    GenerateConfig,
    Node,
    RespondConfig,
    RespondNode,
    RuleConfig,
    RuleNode,
    SlotValidator,
    SubflowConfig,
    SubflowNode,
    ToolConfig,
    ToolNode,
    VerifyConfig,
    VerifyNode,
    WriteToolConfig,
    WriteToolNode,
    node_kind,
)
from agent_core.domain.outcomes import (
    DECLARABLE,
    Awaiting,
    Command,
    Mode,
    Outcome,
    ReasonCode,
    ReasonCodeStr,
    is_declarable,
)
from agent_core.domain.refs import (
    AgentSelector,
    EntityKind,
    EntityRef,
    RefSpec,
    iter_refspecs,
    require_exact_refs,
)
from agent_core.domain.schema import check_output, unsupported_keyword
from agent_core.domain.shared import (
    EscalationRequest,
    Fingerprint,
    OutboxMessage,
    RejectedDraft,
    ToolStatus,
    TranscriptEntry,
    TranscriptRef,
)
from agent_core.domain.state import (
    Action,
    ActionState,
    ActiveFlow,
    BudgetsUsed,
    Decision,
    EncryptedBlob,
    Fact,
    FactSource,
    InvalidationReason,
    PendingIntent,
    RunState,
    RunStatus,
    Slot,
)
from agent_core.domain.turn import (
    ConfirmAnswer,
    ConfirmationPrompt,
    Message,
    RunInput,
    RunResult,
    StepUpPrompt,
    TurnInput,
    TurnResult,
)
from agent_core.domain.version import (
    SCHEMA_VERSION,
)

__all__ = [
    "DECLARABLE", "ENTITY_KIND", "EVENT_EMITTERS", "EVENT_TYPES", "MEASURED_FIELDS", "MVP_NODE_KINDS",
    "PROBLEM_STATUS", "PRODUCTION_NODE_KINDS", "RESULTS", "SCHEMA_VERSION", "TERMINAL", "WAITING",
    "AccessDenied", "AccessDeniedPayload", "AccessDeniedReason", "Action", "ActionCancelled",
    "ActionCancelledPayload", "ActionConfirmed", "ActionConfirmedPayload", "ActionDispatched",
    "ActionDispatchedPayload", "ActionSpec", "ActionState", "ActionVerified", "ActionVerifiedPayload",
    "ActiveFlow", "Agent", "AgentNode", "AgentNodeConfig", "AgentSelector", "AgentStep", "AgentStepPayload",
    "AnyEvent", "Approver",
    "AuthInfo", "AuthLevel", "AwaitApprovalConfig", "AwaitApprovalNode", "Awaiting", "Budgets",
    "BudgetsUsed", "CalibrationRef", "CollectConfig", "CollectNode", "Command", "CommandEmitted",
    "CommandEmittedPayload", "ConfirmAnswer", "ConfirmConfig", "ConfirmNode", "ConfirmationPrompt",
    "CredentialsInvalid", "DecideConfig", "DecideNode", "Decision", "DecisionMade", "DecisionMadePayload",
    "DecisionModelDef", "DomainError", "EncryptedBlob", "EndConfig", "EndNode", "EngineError",
    "EngineEvent", "EngineTemplates", "EntityId", "EntityKind", "EntityRef", "EscalateAction",
    "EscalateConfig", "EscalateNode", "Escalated", "EscalatedPayload", "EscalationRequest", "ExactVersion",
    "ExpiryEvaluated", "ExpiryEvaluatedPayload", "Fact", "FactSource", "Fingerprint", "Flow",
    "GatewayError", "GatewayErrorKind", "GenerateConfig", "GuardsOutput", "HandoffCreatedPayload",
    "HandoffResolved", "HandoffResolvedPayload", "IllegalTransition", "InjectionFlagged",
    "InjectionFlaggedPayload", "InjectionGuard", "InjectionRule", "InjectionRuleset", "Interrupt",
    "InvalidRuntimeRef", "InvalidationReason", "JsonValue", "KnowledgePage", "KnowledgeSnapshot",
    "LabelScore", "LangGuard", "LangScore",
    "LanguageDetection", "LlmUsage", "Locale", "Message", "Mode", "Model", "ModelPrice", "ModelProfile",
    "MutableModel", "Node", "NodeEntered", "NodeEnteredPayload", "NodeId", "OnBehalfOf", "OutboxMessage",
    "Outcome", "PendingIntent", "Policy", "Principal", "PrincipalKey", "PrincipalType", "Probability",
    "ProblemCode", "Prompt", "ProviderSpec", "ReasonCode", "ReasonCodeStr", "RefSpec", "RegistryEntity",
    "RejectedDraft", "Release", "RespondConfig", "RespondNode", "ResponseEmitted", "ResponseEmittedPayload",
    "ResponseFailed", "ResponseFailedPayload",
    "RiskClass", "RuleConfig", "RuleEvaluated", "RuleEvaluatedPayload", "RuleNode", "RunClosed",
    "RunClosedPayload", "RunInput", "RunResult", "RunStarted", "RunStartedPayload", "RunState", "RunStatus",
    "SchemaError", "Slot", "SlotValidator", "StartFlowAction", "StepUpPrompt", "StepUpRequested",
    "StepUpRequestedPayload", "StructuredMode", "SubflowConfig", "SubflowNode", "SubjectRef", "Template",
    "ToolCalled", "ToolCalledPayload", "ToolConfig", "ToolDef", "ToolNode", "ToolStatus", "TranscriptEntry",
    "TranscriptRef", "TurnCompleted", "TurnCompletedPayload", "TurnInProgress", "TurnInput", "TurnResult",
    "TurnStages", "TurnStarted", "TurnStartedPayload", "UtcDatetime", "ValidatorOutcome", "VerifyConfig",
    "VerifyNode", "VersionConflict", "WriteToolConfig", "WriteToolNode", "canonical_bytes", "check_output",
    "dumps",    "is_declarable", "iter_refspecs", "loads", "node_kind", "require_exact_refs", "sha256_hex",
    "to_jsonable", "unsupported_keyword",
]
